---
title: "International Women's Day 2017"
---

The UNSW School of Psychology celebrated International Women's Day by featuring some of our leading female researchers.

By viewing any of the profiles listed below, you will gain an insight into the type of research taking place at UNSW by female researchers; in addition to their individual experience with research within the school.

- [Dr Sophie Li](./sophie-li.html) investigates the role of ovarian hormones in the development and maintenance of anxiety disorders and fatigue related states.

- [Dr Kelly Clemens](./kelly-clemens.html) investigates the behavioural and neural consequences of drug addiction.

- [A/Prof Jessica Grisham](./jessica-grisham.html) investigates obsessive-compulsive disorder, hoarding disorder and related disorders.

- [Dr Kristy Martire](./kristy-martire.html) is a forensic psychologist who trains students in the Master of Psychology (Forensic) Program. Kristy also examines the role and comprehension of expert evidence in criminal trials.

- [Prof Skye McDonald](./skye-mcdonald.html) conducts research in neuropsychology, essentially concerned with disorders that arise from brain dysfunction due to structural or developmental conditions

For anyone considering doing research as a career, the following video produced by [Moving Ahead: Centre for Research Excellence](http://www.psy.unsw.edu.au/research/research-resources/nhmrc-centre-research-excellence-brain-recovery) provides some excellent advice:

<iframe width="560" height="315" src="https://www.youtube.com/embed/b_H2u6Kv1z0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
